CREATE TABLE IF NOT EXISTS `tb_produto_grupo` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(100) NULL COMMENT '',
  `DESCRICAO` VARCHAR(250) NULL COMMENT '',
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS tb_produto_sub_gupo (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ID_PRODUTO_GRUPO` INT NOT NULL COMMENT '',
  `NOME` VARCHAR(100) NULL COMMENT '',
  `DESCRICAO` VARCHAR(250) NULL COMMENT '',
  PRIMARY KEY (`ID`),
  INDEX `fk_PRODUTO_SUBGRUPO_PRODUTO_GRUPO1_idx` (`ID_PRODUTO_GRUPO` ASC),
  CONSTRAINT `fk_PRODUTO_SUBGRUPO_PRODUTO_GRUPO1`
    FOREIGN KEY (`ID_PRODUTO_GRUPO`)
    REFERENCES `tb_produto_grupo` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS tb_produto_marca (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(100) NULL COMMENT '',
  `DESCRICAO` VARCHAR(250) NULL COMMENT '',
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS tb_produto_unidade (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `SIGLA` VARCHAR(10) NULL COMMENT '',
  `DESCRICAO` VARCHAR(250) NULL COMMENT '',
  `PODE_FRACIONAR` CHAR(1) NULL COMMENT '',
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS tb_tribut_icms_custom_cab (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `DESCRICAO` VARCHAR(100) NULL COMMENT '',
  `ORIGEM_MERCADORIA` CHAR(1) NULL COMMENT '',
  PRIMARY KEY (`ID`))
COMMENT = 'Caso a configuração do ICMS precise ser \'customizada\' para determinado produto, utiliza-se essa tabela e sua \'filha\'.'
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;


CREATE TABLE IF NOT EXISTS tb_tribut_grupo_tributario (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DESCRICAO` VARCHAR(100) NULL COMMENT '',
  `ORIGEM_MERCADORIA` CHAR(1) NULL COMMENT '',
  `OBSERVACAO` TEXT NULL COMMENT '',
  PRIMARY KEY (`ID`))
COMMENT = 'Esta tabela irá armazenar os Perfis tributários diferentes existentes dentro do mix de produtos da empresa. Ou seja, os diferentes conjuntos de produtos cuja tributação sofrem variações. Definindo o GRUPO TRIBUTÁRIO (independente da classificação de grupo gerencial empregada pelo cliente). Isto é, produtos com tributações idênticas ficariam todos em um grupo independentemente suas características intrínsecas.\n\nExemplos:\n1. Produtos de fabricação própria (sujeitos ao ICMS ST)\n2. Produtos de Revenda (sujeitos ao Regime do ICMS ST)\n3. Produtos de Revenda Não sujeitos ao ICMS ST\n4. Produtos com Suspensao de IPI\n5. Produtos com Suspensao de PIS, COFINS\n6. etc.\n'
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;


CREATE TABLE IF NOT EXISTS tb_produto (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ID_PRODUTO_SUBGRUPO` INT NOT NULL COMMENT '',
  `ID_PRODUTO_MARCA` INT NOT NULL COMMENT '',
  `ID_PRODUTO_UNIDADE` INT NOT NULL COMMENT '',
  `ID_TRIBUT_ICMS_CUSTOM_CAB` INT UNSIGNED NULL COMMENT '',
  `ID_TRIBUT_GRUPO_TRIBUTARIO` INT NULL COMMENT '',
  `NOME` VARCHAR(100) NULL COMMENT '',
  `DESCRICAO` VARCHAR(250) NULL COMMENT '',
  `GTIN` VARCHAR(14) NULL COMMENT '',
  `CODIGO_INTERNO` VARCHAR(50) NULL COMMENT '',
  `VALOR_COMPRA` DECIMAL(18,6) NULL COMMENT '',
  `VALOR_VENDA` DECIMAL(18,6) NULL COMMENT '',
  `CODIGO_NCM` VARCHAR(8) NULL COMMENT '',
  `ESTOQUE_MINIMO` DECIMAL(18,6) NULL COMMENT '',
  `ESTOQUE_MAXIMO` DECIMAL(18,6) NULL COMMENT '',
  `QUANTIDADE_ESTOQUE` DECIMAL(18,6) NULL COMMENT '',
  `DATA_CADASTRO` DATE NULL COMMENT '',
  PRIMARY KEY (`ID`),
  INDEX `fk_PRODUTO_PRODUTO_SUBGRUPO1_idx` (`ID_PRODUTO_SUBGRUPO` ASC),
  INDEX `fk_PRODUTO_PRODUTO_MARCA1_idx` (`ID_PRODUTO_MARCA` ASC),
  INDEX `fk_PRODUTO_PRODUTO_UNIDADE1_idx` (`ID_PRODUTO_UNIDADE` ASC),
  INDEX `fk_PRODUTO_TRIBUT_ICMS_CUSTOM_CAB1_idx` (`ID_TRIBUT_ICMS_CUSTOM_CAB` ASC),
  INDEX `fk_PRODUTO_TRIBUT_GRUPO_TRIBUTARIO1_idx` (`ID_TRIBUT_GRUPO_TRIBUTARIO` ASC),
  CONSTRAINT `fk_PRODUTO_PRODUTO_SUBGRUPO1`
    FOREIGN KEY (`ID_PRODUTO_SUBGRUPO`)
    REFERENCES `tb_produto_sub_gupo` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRODUTO_PRODUTO_MARCA1`
    FOREIGN KEY (`ID_PRODUTO_MARCA`)
    REFERENCES `tb_produto_marca` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRODUTO_PRODUTO_UNIDADE1`
    FOREIGN KEY (`ID_PRODUTO_UNIDADE`)
    REFERENCES `tb_produto_unidade` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRODUTO_TRIBUT_ICMS_CUSTOM_CAB1`
    FOREIGN KEY (`ID_TRIBUT_ICMS_CUSTOM_CAB`)
    REFERENCES `tb_tribut_icms_custom_cab` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRODUTO_TRIBUT_GRUPO_TRIBUTARIO1`
    FOREIGN KEY (`ID_TRIBUT_GRUPO_TRIBUTARIO`)
    REFERENCES `tb_tribut_grupo_tributario` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;